# Auto-generated by: aris completion --generate-cache
# Do not edit manually — regenerated by: aris --refresh

_aris_complete_cached() {
  local cur prev
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  # Subcommands and flags
  local subcmds="search completion --refresh --list --help --config --open --add --revert --reset-config"

  # Map of script names/shortcuts to their execution paths
  declare -A script_paths=(
  )

  # Map of script names -> option flags (space-separated)
  declare -A script_options=(
  )

  if [[ $COMP_CWORD -eq 1 ]]; then
    # First argument: complete subcommands, flags, script names, and groups
    local all_options="$subcmds  "
    COMPREPLY=( $(compgen -W "$all_options" -- "$cur") )
    return 0
  elif [[ $COMP_CWORD -ge 2 ]]; then
    # Check if the first argument is a script with an execution_path
    local script_name="${COMP_WORDS[1]}"
    if [[ -n "${script_paths[$script_name]:-}" ]]; then
      # If user is typing an option (starts with -), offer script-specific flags
      if [[ "$cur" == -* ]]; then
        local opts="${script_options[$script_name]:-}"
        if [[ -n "$opts" ]]; then
          COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
          return 0
        fi
      fi

      # Complete files/directories from BOTH execution_path and current directory
      local exec_path="${script_paths[$script_name]}"
      local current_pwd="$PWD"
      local completions_exec=()
      local completions_cwd=()

      # Get completions from execution_path
      cd "$exec_path" 2>/dev/null && {
        completions_exec=( $(compgen -f -- "$cur") )
        cd "$current_pwd"
      }

      # Get completions from current working directory
      completions_cwd=( $(compgen -f -- "$cur") )

      # Combine both sets, removing duplicates
      local combined=()
      local seen=()

      for item in "${completions_exec[@]}"; do
        combined+=("$item")
        seen+=("$item")
      done

      for item in "${completions_cwd[@]}"; do
        local is_duplicate=0
        for seen_item in "${seen[@]}"; do
          if [[ "$item" == "$seen_item" ]]; then
            is_duplicate=1
            break
          fi
        done
        if [[ $is_duplicate -eq 0 ]]; then
          combined+=("$item")
        fi
      done

      COMPREPLY=( "${combined[@]}" )
      return 0
    fi
  fi

  # Default: file/directory completion from current directory
  COMPREPLY=( $(compgen -f -- "$cur") )
  return 0
}
