#compdef aris
# Auto-generated zsh completion cache
# Do not edit manually — regenerated by: aris --refresh

# Global associative array for exec paths (defined once)
typeset -gA _aris_exec_paths
_aris_exec_paths=(

)

# Global mapping script -> option flags (space-separated)
typeset -gA _aris_opt_args
_aris_opt_args=(

)

_aris_complete_cached() {
  local curcontext="$curcontext" state line ret=1
  local cur_word
  cur_word="${words[CURRENT]}"
  local -a subcmds script_items group_items

  # System commands and flags
  subcmds=(
    'search:search for scripts in the collection'
    'completion:manage shell completion'
    '--refresh:refresh script cache and regenerate completions'
    '--list:list all available scripts'
    '--help:show help message'
    '--config:open config file in editor'
    '--open:open script execution path'
    '--add:add a new script to the collection'
    '--revert:revert recent changes to config'
    '--reset-config:reset config to default state'
  )

  # All script names and shortcuts with descriptions
  script_items=(

  )

  # Group names
  group_items=(

  )

  # Completion logic based on cursor position
  if (( CURRENT == 2 )); then
    _describe -t commands 'commands' subcmds && ret=0
    _describe -t scripts 'scripts' script_items && ret=0
    _describe -t groups 'groups' group_items && ret=0
    return ret
  elif (( CURRENT >= 3 )); then
    local script_name="${words[2]}"
    local exec_path="${_aris_exec_paths[$script_name]:-}"

    # If user is typing an option (starts with -), offer script-specific flags
    if [[ "$cur_word" == -* ]]; then
      local opts_str="${_aris_opt_args[$script_name]:-}"
      if [[ -n "$opts_str" ]]; then
        local -a opts_array
        opts_array=(${(s: :)opts_str})
        compadd -- ${opts_array[@]} && ret=0
        return ret
      fi
    fi

    if [[ -n "$exec_path" && -d "$exec_path" ]]; then
      _alternative         "exec-files:files from execution path:_files -W "$exec_path""         "local-files:files from current directory:_files" && ret=0
      return ret
    else
      _files && ret=0
      return ret
    fi
  fi

  return ret
}
