# aris-cli zsh completion stub (lazy-loaded, no Python at startup)
# Generated by: aris completion --generate-stub
#
# Source this file in ~/.zshrc:
#   source "/home/ap/cloud/ARIS/aris-cli/logs/.completion_stub.zsh"

export ARIS_ROOT="/home/ap/cloud/ARIS/aris-cli"

_aris_complete() {
  local cache="$ARIS_ROOT/logs/.completion_cache.zsh"
  local need_load=0
  local current_mtime

  # Check if cache needs (re)loading by comparing file mtime
  if [[ -z "${_ARIS_CACHE_MTIME:-}" ]]; then
    need_load=1
  elif [[ -f "$cache" ]]; then
    current_mtime=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    [[ "$current_mtime" != "$_ARIS_CACHE_MTIME" ]] && need_load=1
  fi

  if (( need_load )); then
    # Generate cache on-the-fly if missing (one-time cost)
    if [[ ! -f "$cache" ]]; then
      "$ARIS_ROOT/run.sh" completion --generate-cache 2>/dev/null
    fi
    
    # Source the cache which defines _aris_complete_cached
    if [[ -f "$cache" ]]; then
      source "$cache"
      _ARIS_CACHE_MTIME=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    fi
  fi

  # Call the cached completion function if loaded
  if (( ${+functions[_aris_complete_cached]} )); then
    _aris_complete_cached
  else
    # Fallback if cache failed to load
    local -a fallback_items
    fallback_items=(
      'search:search for scripts'
      'completion:manage completions'
      '--refresh:refresh script cache'
      '--list:list available scripts'
      '--help:show help'
      '--config:open config'
    )
    _describe 'aris commands' fallback_items
  fi
}

# Register the completion function for the command 'aris'
compdef _aris_complete aris
