# aris-cli bash completion stub (lazy-loaded, no Python at startup)
# Generated by: aris completion --generate-stub
#
# Source this file in ~/.bashrc:
#   source "/home/ap/cloud/ARIS/aris-cli/logs/.completion_stub.bash"

export ARIS_ROOT="/home/ap/cloud/ARIS/aris-cli"

_aris_complete() {
  local cache="$ARIS_ROOT/logs/.completion_cache.bash"

  # Check if cache needs (re)loading by comparing file mtime.
  # stat is a single syscall — effectively free on every TAB press.
  local need_load=0
  if [[ -z "${_ARIS_CACHE_MTIME:-}" ]]; then
    need_load=1
  elif [[ -f "$cache" ]]; then
    local current_mtime
    current_mtime=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    [[ "$current_mtime" != "$_ARIS_CACHE_MTIME" ]] && need_load=1
  fi

  if [[ $need_load -eq 1 ]]; then
    # Generate cache on-the-fly if missing (one-time cost)
    if [[ ! -f "$cache" ]]; then
      "$ARIS_ROOT/run.sh" completion --generate-cache 2>/dev/null
    fi
    if [[ -f "$cache" ]]; then
      source "$cache"
      _ARIS_CACHE_MTIME=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    fi
  fi

  # Call the cached completion function, or fall back to basics
  if type _aris_complete_cached &>/dev/null; then
    _aris_complete_cached
  else
    COMPREPLY=( $(compgen -W "search completion --refresh --list --help --config --open --add --revert --reset-config" -- "${COMP_WORDS[COMP_CWORD]}") )
  fi
}
complete -o filenames -F _aris_complete aris
