#compdef aris
# Auto-generated zsh completion cache
# Do not edit manually — regenerated by: aris --refresh

# Global associative array for exec paths (defined once)
typeset -gA _aris_exec_paths
_aris_exec_paths=(
    '0_summarise_imgs_and_annots.py' '/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
    'summar' '/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
    '1_organize_into_images_annots.py' '/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
    'organize_folder' '/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
    '2_rename_files.py' '/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
    'rename_files' '/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
    '3_validate_data_structure.py' '/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
    'validate' '/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
    'analyze_synth_base_images.py' '/home/ap/cloud/ARIS/aris-cli/scripts'
    'build_inference_records.py' '/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
    'check_and_move_images.py' '/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
    'check_and_move_images' '/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
    'collection_annots_overview.py' '/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
    'compare_images_between_two_dirs.py' '/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
    'config_backup.py' '/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
    'dataset_gen.sh' '/home/ap/cloud/master/aris_master'
    'detection_annotator.py' '/home/ap/cloud/ARIS/repositories/DW_Pictogram_Detection'
    'filter_synth_images.py' '/home/ap/cloud/ARIS/aris-cli/scripts'
    'find_duplicate_imgs_in_collection.py' '/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
    'fix_category_annotations.py' '/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
    'generate_config_summary.py' '/home/ap/cloud/master/aris_master'
    'generate_data_yaml_with_log.py' '/home/ap/cloud/ARIS/aris-cli/scripts/classification'
    'image_sorter.sh' '/home/ap/cloud/ARIS/image-sorter'
    'sort' '/home/ap/cloud/ARIS/image-sorter'
    'keep_newest_duplicates.py' '/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
    'merge_annots_from_tags.py' '/home/ap/cloud/ARIS/aris-cli/scripts'
    'merge_captures.py' '/home/ap/cloud/ARIS/aris-cli/scripts'
    'move_n_random_images_to_val.py' '/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
    'review_annotations.py' '/home/ap/Documents/ARIS/Annotation'
    'review_img_annots_pairs.py' '/home/ap/cloud/ARIS/aris-cli/scripts'
    'segment.py' '/home/ap/Documents/ARIS/Annotation'
    'sort_images_from_insights.py' '/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
    'sync_and_sort_images.sh' '/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
    'sync' '/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
    'sync_image_files.py' '/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
    'train_conditional_notesmd_test.py' '/home/ap/cloud/master/aris_master'
    'txt_file_path_manipulation.py' '/home/ap/cloud/ARIS/aris-cli/scripts'
    'update_bulk_download.py' '/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
)

_aris_complete_cached() {
  local curcontext="$curcontext" state line ret=1
  typeset -A opt_args
  local -a subcmds script_items group_items

  # System commands and flags
  subcmds=(
    'search:search for scripts in the collection'
    'completion:manage shell completion'
    '--refresh:refresh script cache and regenerate completions'
    '--list:list all available scripts'
    '--help:show help message'
    '--config:open config file in editor'
    '--open:open script execution path'
    '--add:add a new script to the collection'
    '--revert:revert recent changes to config'
    '--reset-config:reset config to default state'
  )

  # All script names and shortcuts with descriptions
  script_items=(
    '0_summarise_imgs_and_annots.py:[the_training_bible/organize_data] 0_summarise_imgs_and_anno'
    'summar:[the_training_bible/organize_data] 0_summarise_imgs_and_anno (shortcut)'
    '1_organize_into_images_annots.py:[the_training_bible/organize_data] 1_organize_into_images_an'
    'organize_folder:[the_training_bible/organize_data] 1_organize_into_images_an (shortcut)'
    '2_rename_files.py:[the_training_bible/organize_data] 2_rename_files.py'
    'rename_files:[the_training_bible/organize_data] 2_rename_files.py (shortcut)'
    '3_validate_data_structure.py:[the_training_bible/organize_data] 3_validate_data_structure'
    'validate:[the_training_bible/organize_data] 3_validate_data_structure (shortcut)'
    'analyze_synth_base_images.py:analyze_synth_base_images.py'
    'build_inference_records.py:[collection_sorter] build_inference_records.py'
    'check_and_move_images.py:[christians_helper_scripts] check_and_move_images.py'
    'check_and_move_images:[christians_helper_scripts] check_and_move_images.py (shortcut)'
    'collection_annots_overview.py:[christians_helper_scripts] collection_annots_overview.py'
    'compare_images_between_two_dirs.py:[christians_helper_scripts] compare_images_between_two_dirs.'
    'config_backup.py:[christians_helper_scripts] config_backup.py'
    'dataset_gen.sh:[aris_master] dataset_gen.sh'
    'detection_annotator.py:[DW_Pictogram_Detection] detection_annotator.py'
    'filter_synth_images.py:filter_synth_images.py'
    'find_duplicate_imgs_in_collection.py:[christians_helper_scripts] find_duplicate_imgs_in_collectio'
    'fix_category_annotations.py:[christians_helper_scripts] fix_category_annotations.py'
    'generate_config_summary.py:[aris_master] generate_config_summary.py'
    'generate_data_yaml_with_log.py:[classification] generate_data_yaml_with_log.py'
    'image_sorter.sh:[image-sorter] image_sorter.sh'
    'sort:[image-sorter] image_sorter.sh (shortcut)'
    'keep_newest_duplicates.py:[collection_sorter] keep_newest_duplicates.py'
    'merge_annots_from_tags.py:merge_annots_from_tags.py'
    'merge_captures.py:merge_captures.py'
    'move_n_random_images_to_val.py:[christians_helper_scripts] move_n_random_images_to_val.py'
    'review_annotations.py:[Annotation] review_annotations.py'
    'review_img_annots_pairs.py:review_img_annots_pairs.py'
    'segment.py:[Annotation] segment.py'
    'sort_images_from_insights.py:[collection_sorter] sort_images_from_insights.py'
    'sync_and_sort_images.sh:[collection_sorter] sync_and_sort_images.sh'
    'sync:[collection_sorter] sync_and_sort_images.sh (shortcut)'
    'sync_image_files.py:[collection_sorter] sync_image_files.py'
    'train_conditional_notesmd_test.py:[aris_master] train_conditional_notesmd_test.py'
    'txt_file_path_manipulation.py:txt_file_path_manipulation.py'
    'update_bulk_download.py:[collection_sorter] update_bulk_download.py'
  )

  # Group names
  group_items=(
    'Annotation:group'
    'aris_master:group'
    'christians_helper_scripts:group'
    'classification:group'
    'collection_sorter:group'
    'DW_Pictogram_Detection:group'
    'image-sorter:group'
    'the_training_bible/organize_data:group'
  )

  # Completion logic based on cursor position
  if (( CURRENT == 2 )); then
    _describe -t commands 'commands' subcmds && ret=0
    _describe -t scripts 'scripts' script_items && ret=0
    _describe -t groups 'groups' group_items && ret=0
    return ret
  elif (( CURRENT >= 3 )); then
    local script_name="${words[2]}"
    local exec_path="${_aris_exec_paths[$script_name]:-}"

    if [[ -n "$exec_path" && -d "$exec_path" ]]; then
      _alternative         "exec-files:files from execution path:_files -W "$exec_path""         "local-files:files from current directory:_files" && ret=0
      return ret
    else
      _files && ret=0
      return ret
    fi
  fi

  return ret
}
