# Auto-generated by: aris completion --generate-cache
# Do not edit manually — regenerated by: aris --refresh

_aris_complete_cached() {
  local cur prev
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  # Subcommands and flags
  local subcmds="search completion --refresh --list --help --config --open --add --revert --reset-config"

  # Map of script names/shortcuts to their execution paths
  declare -A script_paths=(
  ["0_summarise_imgs_and_annots.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
  ["summar"]='/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
  ["1_organize_into_images_annots.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
  ["organize_folder"]='/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
  ["2_rename_files.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
  ["rename_files"]='/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
  ["3_validate_data_structure.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
  ["validate"]='/home/ap/cloud/ARIS/aris-cli/scripts/the_training_bible/organize_data'
  ["analyze_synth_base_images.py"]='/home/ap/cloud/ARIS/aris-cli/scripts'
  ["build_inference_records.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
  ["check_and_move_images.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
  ["check_and_move_images"]='/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
  ["collection_annots_overview.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
  ["compare_images_between_two_dirs.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
  ["config_backup.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
  ["dataset_gen.sh"]='/home/ap/cloud/master/aris_master'
  ["detection_annotator.py"]='/home/ap/cloud/ARIS/repositories/DW_Pictogram_Detection'
  ["filter_synth_images.py"]='/home/ap/cloud/ARIS/aris-cli/scripts'
  ["find_duplicate_imgs_in_collection.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
  ["fix_category_annotations.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
  ["generate_config_summary.py"]='/home/ap/cloud/master/aris_master'
  ["generate_data_yaml_with_log.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/classification'
  ["image_sorter.sh"]='/home/ap/cloud/ARIS/image-sorter'
  ["sort"]='/home/ap/cloud/ARIS/image-sorter'
  ["keep_newest_duplicates.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
  ["merge_annots_from_tags.py"]='/home/ap/cloud/ARIS/aris-cli/scripts'
  ["merge_captures.py"]='/home/ap/cloud/ARIS/aris-cli/scripts'
  ["move_n_random_images_to_val.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/christians_helper_scripts'
  ["review_annotations.py"]='/home/ap/Documents/ARIS/Annotation'
  ["review_img_annots_pairs.py"]='/home/ap/cloud/ARIS/aris-cli/scripts'
  ["segment.py"]='/home/ap/Documents/ARIS/Annotation'
  ["sort_images_from_insights.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
  ["sync_and_sort_images.sh"]='/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
  ["sync"]='/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
  ["sync_image_files.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
  ["train_conditional_notesmd_test.py"]='/home/ap/cloud/master/aris_master'
  ["txt_file_path_manipulation.py"]='/home/ap/cloud/ARIS/aris-cli/scripts'
  ["update_bulk_download.py"]='/home/ap/cloud/ARIS/aris-cli/scripts/collection_sorter'
  )

  if [[ $COMP_CWORD -eq 1 ]]; then
    # First argument: complete subcommands, flags, script names, and groups
    local all_options="$subcmds 0_summarise_imgs_and_annots.py 1_organize_into_images_annots.py 2_rename_files.py 3_validate_data_structure.py analyze_synth_base_images.py build_inference_records.py check_and_move_images check_and_move_images.py collection_annots_overview.py compare_images_between_two_dirs.py config_backup.py dataset_gen.sh detection_annotator.py filter_synth_images.py find_duplicate_imgs_in_collection.py fix_category_annotations.py generate_config_summary.py generate_data_yaml_with_log.py image_sorter.sh keep_newest_duplicates.py merge_annots_from_tags.py merge_captures.py move_n_random_images_to_val.py organize_folder rename_files review_annotations.py review_img_annots_pairs.py segment.py sort sort_images_from_insights.py summar sync sync_and_sort_images.sh sync_image_files.py train_conditional_notesmd_test.py txt_file_path_manipulation.py update_bulk_download.py validate Annotation aris_master christians_helper_scripts classification collection_sorter DW_Pictogram_Detection image-sorter the_training_bible/organize_data"
    COMPREPLY=( $(compgen -W "$all_options" -- "$cur") )
    return 0
  elif [[ $COMP_CWORD -ge 2 ]]; then
    # Check if the first argument is a script with an execution_path
    local script_name="${COMP_WORDS[1]}"
    if [[ -n "${script_paths[$script_name]:-}" ]]; then
      # Complete files/directories from BOTH execution_path and current directory
      local exec_path="${script_paths[$script_name]}"
      local current_pwd="$PWD"
      local completions_exec=()
      local completions_cwd=()

      # Get completions from execution_path
      cd "$exec_path" 2>/dev/null && {
        completions_exec=( $(compgen -f -- "$cur") )
        cd "$current_pwd"
      }

      # Get completions from current working directory
      completions_cwd=( $(compgen -f -- "$cur") )

      # Combine both sets, removing duplicates
      local combined=()
      local seen=()

      for item in "${completions_exec[@]}"; do
        combined+=("$item")
        seen+=("$item")
      done

      for item in "${completions_cwd[@]}"; do
        local is_duplicate=0
        for seen_item in "${seen[@]}"; do
          if [[ "$item" == "$seen_item" ]]; then
            is_duplicate=1
            break
          fi
        done
        if [[ $is_duplicate -eq 0 ]]; then
          combined+=("$item")
        fi
      done

      COMPREPLY=( "${combined[@]}" )
      return 0
    fi
  fi

  # Default: file/directory completion from current directory
  COMPREPLY=( $(compgen -f -- "$cur") )
  return 0
}
