# ---------------------------------------------------------------------------
# File: src/completion.py
# ---------------------------------------------------------------------------
"""Shell completion helpers — fast, lazy-loaded architecture (bash + zsh).

Architecture (zero Python calls at shell startup):

1. A tiny shell stub is generated once and sourced by ~/.bashrc or ~/.zshrc.
   It defines a lazy-loading wrapper — NO Python is called at shell startup.

2. On first TAB press, the wrapper sources a pre-generated cache file
   containing the full completion function with all script names baked in.
   The cache file is pure shell code — sourcing it is effectively instant.

3. The cache is regenerated by `aris --refresh` or
   `aris completion --generate-cache`.  If the cache file is missing on
   first TAB, it is generated on-the-fly (one-time cost).

4. The wrapper detects when the cache file's mtime changes (single
   stat syscall — nanoseconds) and re-sources it automatically, so
   `aris --refresh` in one terminal updates completions everywhere.

Generated files:
  Bash:
    logs/.completion_stub.bash  — tiny stub sourced by ~/.bashrc
    logs/.completion_cache.bash — full completion data, lazy-loaded on first TAB
  Zsh:
    logs/.completion_stub.zsh   — tiny stub sourced by ~/.zshrc
    logs/.completion_cache.zsh  — full completion data, lazy-loaded on first TAB
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Stub generator (lightweight — no heavy imports needed)
# ---------------------------------------------------------------------------

def bash_stub(root: Path) -> str:
    """Generate the lightweight bash stub for ~/.bashrc sourcing.

    This stub:
    - Exports ARIS_ROOT
    - Registers a lazy-loading completion function
    - On first TAB: sources the pre-generated cache
    - On subsequent TABs: calls the cached function directly
    - Detects cache file mtime changes to auto-reload after `aris --refresh`

    No Python is called at shell startup or on TAB (unless cache is missing).

    Args:
        root: ARIS CLI repo root.

    Returns:
        Bash stub script as string.
    """
    root_str = str(root)
    return f'''# aris-cli bash completion stub (lazy-loaded, no Python at startup)
# Generated by: aris completion --generate-stub
#
# Source this file in ~/.bashrc:
#   source "{root_str}/logs/.completion_stub.bash"

export ARIS_ROOT="{root_str}"

_aris_complete() {{
  local cache="$ARIS_ROOT/logs/.completion_cache.bash"

  # Check if cache needs (re)loading by comparing file mtime.
  # stat is a single syscall — effectively free on every TAB press.
  local need_load=0
  if [[ -z "${{_ARIS_CACHE_MTIME:-}}" ]]; then
    need_load=1
  elif [[ -f "$cache" ]]; then
    local current_mtime
    current_mtime=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    [[ "$current_mtime" != "$_ARIS_CACHE_MTIME" ]] && need_load=1
  fi

  if [[ $need_load -eq 1 ]]; then
    # Generate cache on-the-fly if missing (one-time cost)
    if [[ ! -f "$cache" ]]; then
      "$ARIS_ROOT/run.sh" completion --generate-cache 2>/dev/null
    fi
    if [[ -f "$cache" ]]; then
      source "$cache"
      _ARIS_CACHE_MTIME=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    fi
  fi

  # Call the cached completion function, or fall back to basics
  if type _aris_complete_cached &>/dev/null; then
    _aris_complete_cached
  else
    COMPREPLY=( $(compgen -W "search completion --refresh --list --help --config --open --add --revert --reset-config" -- "${{COMP_WORDS[COMP_CWORD]}}") )
  fi
}}
complete -o filenames -F _aris_complete aris
'''


def zsh_stub(root: Path) -> str:
    """Generate the lightweight zsh stub for ~/.zshrc sourcing.

    This stub:
    - Exports ARIS_ROOT
    - Registers a lazy-loading completion function via compdef
    - On first TAB: sources the pre-generated cache
    - On subsequent TABs: calls the cached function directly
    - Detects cache file mtime changes to auto-reload after `aris --refresh`

    No Python is called at shell startup or on TAB (unless cache is missing).

    Args:
        root: ARIS CLI repo root.

    Returns:
        Zsh stub script as string.
    """
    root_str = str(root)
    return f'''# aris-cli zsh completion stub (lazy-loaded, no Python at startup)
# Generated by: aris completion --generate-stub
#
# Source this file in ~/.zshrc:
#   source "{root_str}/logs/.completion_stub.zsh"

export ARIS_ROOT="{root_str}"

_aris_complete() {{
  local cache="$ARIS_ROOT/logs/.completion_cache.zsh"
  local need_load=0
  local current_mtime

  # Check if cache needs (re)loading by comparing file mtime
  if [[ -z "${{_ARIS_CACHE_MTIME:-}}" ]]; then
    need_load=1
  elif [[ -f "$cache" ]]; then
    current_mtime=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    [[ "$current_mtime" != "$_ARIS_CACHE_MTIME" ]] && need_load=1
  fi

  if (( need_load )); then
    # Generate cache on-the-fly if missing (one-time cost)
    if [[ ! -f "$cache" ]]; then
      "$ARIS_ROOT/run.sh" completion --generate-cache 2>/dev/null
    fi
    
    # Source the cache which defines _aris_complete_cached
    if [[ -f "$cache" ]]; then
      source "$cache"
      _ARIS_CACHE_MTIME=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    fi
  fi

  # Call the cached completion function if loaded
  if (( ${{+functions[_aris_complete_cached]}} )); then
    _aris_complete_cached
  else
    # Fallback if cache failed to load
    local -a fallback_items
    fallback_items=(
      'search:search for scripts'
      'completion:manage completions'
      '--refresh:refresh script cache'
      '--list:list available scripts'
      '--help:show help'
      '--config:open config'
    )
    _describe 'aris commands' fallback_items
  fi
}}

# Register the completion function for the command 'aris'
compdef _aris_complete aris
'''


# ---------------------------------------------------------------------------
# Cache generator (heavy imports deferred to here)
# ---------------------------------------------------------------------------

def _generate_cache_content(root: Path) -> str:
    """Generate the full completion function for caching.

    Reads from config.yaml only (no filesystem scanning) for speed.
    Called only by --generate-cache, not at shell startup.

    Args:
        root: ARIS CLI repo root.

    Returns:
        Bash completion function as string.
    """
    # Heavy imports — only loaded when actually generating the cache
    from utils import load_config

    cfg = load_config(root)

    # Use config data directly - no filesystem scanning
    entries = cfg.get("scripts", [])

    # Collect script names/shortcuts and group names
    names: list[str] = []
    groups: set[str] = set()
    for e in entries:
        name = e.get("name", "")
        if name:
            names.append(name)
        shortcut = e.get("shortcut", "")
        if shortcut:
            names.append(shortcut)
        group = e.get("group", "")
        if group:
            groups.add(group)

    script_names = " ".join(sorted(set(names), key=str.lower))
    group_names = " ".join(sorted(groups, key=str.lower))

    # Build exec-paths map
    script_exec_paths: dict[str, str] = {}
    for e in entries:
        name = e.get("name", "")
        exec_path = e.get("execution_path", "")
        if name and exec_path:
            script_exec_paths[name] = exec_path
            shortcut = e.get("shortcut", "")
            if shortcut:
                script_exec_paths[shortcut] = exec_path

    exec_paths_bash = ""
    for name, path in script_exec_paths.items():
        exec_paths_bash += f'  ["{name}"]={path!r}\n'

    # Build per-script options map by running scripts with --help
    # Use argparse_completion_utils for robust extraction
    try:
      from argparse_completion_utils import build_script_options_map
      options_map = build_script_options_map(entries)
    except Exception as e:
      print(f"Error occurred while building script options map:")
      print(f"Error details: {e}", file=sys.stderr)
      options_map = {}

    options_bash = ""
    for name, opts in options_map.items():
      opts_str = " ".join(opts) if opts else ""
      options_bash += f'  ["{name}"]={opts_str!r}\n'

    return f'''# Auto-generated by: aris completion --generate-cache
# Do not edit manually — regenerated by: aris --refresh

_aris_complete_cached() {{
  local cur prev
  COMPREPLY=()
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  prev="${{COMP_WORDS[COMP_CWORD-1]}}"

  # Subcommands and flags
  local subcmds="search completion --refresh --list --help --config --open --add --revert --reset-config"

  # Map of script names/shortcuts to their execution paths
  declare -A script_paths=(
{exec_paths_bash}  )

  # Map of script names -> option flags (space-separated)
  declare -A script_options=(
{options_bash}  )

  if [[ $COMP_CWORD -eq 1 ]]; then
    # First argument: complete subcommands, flags, script names, and groups
    local all_options="$subcmds {script_names} {group_names}"
    COMPREPLY=( $(compgen -W "$all_options" -- "$cur") )
    return 0
  elif [[ $COMP_CWORD -ge 2 ]]; then
    # Check if the first argument is a script with an execution_path
    local script_name="${{COMP_WORDS[1]}}"
    if [[ -n "${{script_paths[$script_name]:-}}" ]]; then
      # If user is typing an option (starts with -), offer script-specific flags
      if [[ "$cur" == -* ]]; then
        local opts="${{script_options[$script_name]:-}}"
        if [[ -n "$opts" ]]; then
          COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
          return 0
        fi
      fi

      # Complete files/directories from BOTH execution_path and current directory
      local exec_path="${{script_paths[$script_name]}}"
      local current_pwd="$PWD"
      local completions_exec=()
      local completions_cwd=()

      # Get completions from execution_path
      cd "$exec_path" 2>/dev/null && {{
        completions_exec=( $(compgen -f -- "$cur") )
        cd "$current_pwd"
      }}

      # Get completions from current working directory
      completions_cwd=( $(compgen -f -- "$cur") )

      # Combine both sets, removing duplicates
      local combined=()
      local seen=()

      for item in "${{completions_exec[@]}}"; do
        combined+=("$item")
        seen+=("$item")
      done

      for item in "${{completions_cwd[@]}}"; do
        local is_duplicate=0
        for seen_item in "${{seen[@]}}"; do
          if [[ "$item" == "$seen_item" ]]; then
            is_duplicate=1
            break
          fi
        done
        if [[ $is_duplicate -eq 0 ]]; then
          combined+=("$item")
        fi
      done

      COMPREPLY=( "${{combined[@]}}" )
      return 0
    fi
  fi

  # Default: file/directory completion from current directory
  COMPREPLY=( $(compgen -f -- "$cur") )
  return 0
}}
'''


def _generate_zsh_cache_content(root: Path) -> str:
    """Generate zsh-specific cache with full completion function.

    Creates a complete zsh completion function using compsys (_describe)
    with all script data baked in. Reads from config.yaml only for speed.

    Args:
        root: ARIS CLI repo root.

    Returns:
        Zsh completion function as string.
    """
    # Heavy imports — only loaded when generating cache
    from utils import load_config

    cfg = load_config(root)

    # Use config data directly - no filesystem scanning
    entries = cfg.get("scripts", [])

    # Build completion arrays for _describe (proper zsh array format)
    script_completions = []
    groups = set()
    for e in entries:
        name = e.get("name", "")
        if not name:
            continue
        base_desc = e.get("description", name)
        group = e.get("group", "")
        if group:
            desc = f"[{group}] {base_desc}"
            groups.add(group)
        else:
            desc = base_desc
        desc = desc[:60].replace("'", "'\\''")
        script_completions.append(f"    '{name}:{desc}'")
        shortcut = e.get("shortcut", "")
        if shortcut:
            script_completions.append(f"    '{shortcut}:{desc} (shortcut)'")

    scripts_list = "\n".join(script_completions)
    group_list = "\n".join([f"    '{g}:group'" for g in sorted(groups, key=str.lower)])

    # Build exec-paths associative array for file completion context
    exec_paths_entries = []
    for e in entries:
        name = e.get("name", "")
        exec_path = e.get("execution_path", "")
        if name and exec_path:
            exec_paths_entries.append(f'    {name!r} {exec_path!r}')
            shortcut = e.get("shortcut", "")
            if shortcut:
                exec_paths_entries.append(f'    {shortcut!r} {exec_path!r}')

    exec_paths_zsh = "\n".join(exec_paths_entries) if exec_paths_entries else ""

    # Build per-script options map for zsh completion
    try:
        from argparse_completion_utils import build_script_options_map
        z_options_map = build_script_options_map(entries)
    except Exception:
        z_options_map = {}

    opt_entries = []
    for name, opts in z_options_map.items():
        opts_str = " ".join(opts) if opts else ""
        opt_entries.append(f'    {name!r} {opts_str!r}')

    opt_entries_zsh = "\n".join(opt_entries) if opt_entries else ""

    return f'''#compdef aris
# Auto-generated zsh completion cache
# Do not edit manually — regenerated by: aris --refresh

# Global associative array for exec paths (defined once)
typeset -gA _aris_exec_paths
_aris_exec_paths=(
{exec_paths_zsh}
)

# Global mapping script -> option flags (space-separated)
typeset -gA _aris_opt_args
_aris_opt_args=(
{opt_entries_zsh}
)

_aris_complete_cached() {{
  local curcontext="$curcontext" state line ret=1
  local cur_word
  cur_word="${{words[CURRENT]}}"
  local -a subcmds script_items group_items

  # System commands and flags
  subcmds=(
    'search:search for scripts in the collection'
    'completion:manage shell completion'
    '--refresh:refresh script cache and regenerate completions'
    '--list:list all available scripts'
    '--help:show help message'
    '--config:open config file in editor'
    '--open:open script execution path'
    '--add:add a new script to the collection'
    '--revert:revert recent changes to config'
    '--reset-config:reset config to default state'
  )

  # All script names and shortcuts with descriptions
  script_items=(
{scripts_list}
  )

  # Group names
  group_items=(
{group_list}
  )

  # Completion logic based on cursor position
  if (( CURRENT == 2 )); then
    _describe -t commands 'commands' subcmds && ret=0
    _describe -t scripts 'scripts' script_items && ret=0
    _describe -t groups 'groups' group_items && ret=0
    return ret
  elif (( CURRENT >= 3 )); then
    local script_name="${{words[2]}}"
    local exec_path="${{_aris_exec_paths[$script_name]:-}}"

    # If user is typing an option (starts with -), offer script-specific flags
    if [[ "$cur_word" == -* ]]; then
      local opts_str="${{_aris_opt_args[$script_name]:-}}"
      if [[ -n "$opts_str" ]]; then
        local -a opts_array
        opts_array=(${{(s: :)opts_str}})
        compadd -- ${{opts_array[@]}} && ret=0
        return ret
      fi
    fi

    if [[ -n "$exec_path" && -d "$exec_path" ]]; then
      _alternative \
        "exec-files:files from execution path:_files -W \"$exec_path\"" \
        "local-files:files from current directory:_files" && ret=0
      return ret
    else
      _files && ret=0
      return ret
    fi
  fi

  return ret
}}
'''


def generate_cache(root: Path) -> None:
    """Generate and write the completion cache files (both bash and zsh).

    Args:
        root: ARIS CLI repo root.
    """
    # Generate bash cache
    bash_content = _generate_cache_content(root)
    bash_cache_path = root / "logs" / ".completion_cache.bash"
    bash_cache_path.parent.mkdir(parents=True, exist_ok=True)
    bash_cache_path.write_text(bash_content)
    
    # Generate zsh cache
    zsh_content = _generate_zsh_cache_content(root)
    zsh_cache_path = root / "logs" / ".completion_cache.zsh"
    zsh_cache_path.parent.mkdir(parents=True, exist_ok=True)
    zsh_cache_path.write_text(zsh_content)


def generate_stub(root: Path, shell: str = "bash") -> None:
    """Generate and write the completion stub file for specified shell.

    Args:
        root: ARIS CLI repo root.
        shell: Shell type ('bash' or 'zsh').
    """
    if shell == "zsh":
        content = zsh_stub(root)
        stub_path = root / "logs" / ".completion_stub.zsh"
    else:
        content = bash_stub(root)
        stub_path = root / "logs" / ".completion_stub.bash"
    
    stub_path.parent.mkdir(parents=True, exist_ok=True)
    stub_path.write_text(content)


def test_zsh_completion(root: Path) -> int:
    """Test zsh completion by simulating tab completion scenarios.

    Args:
        root: ARIS CLI repo root.

    Returns:
        Exit code (0 on success).
    """
    print("Testing zsh completion...")
    print()
    
    # Check files exist
    stub_path = root / "logs" / ".completion_stub.zsh"
    cache_path = root / "logs" / ".completion_cache.zsh"
    
    if not stub_path.exists():
        print(f"❌ Stub file missing: {stub_path}")
        return 1
    print(f"✓ Stub file exists: {stub_path}")
    
    if not cache_path.exists():
        print(f"❌ Cache file missing: {cache_path}")
        return 1
    print(f"✓ Cache file exists: {cache_path}")
    print()
    
    # Test zsh syntax
    import subprocess
    result = subprocess.run(
        ["zsh", "-n", str(stub_path)],
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        print(f"❌ Stub syntax error: {result.stderr}")
        return 1
    print(f"✓ Stub syntax is valid")
    
    result = subprocess.run(
        ["zsh", "-n", str(cache_path)],
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        print(f"❌ Cache syntax error: {result.stderr}")
        return 1
    print(f"✓ Cache syntax is valid")
    print()
    
    # Test completion generation works
    print("Testing completion function execution...")
    test_script = f'''
# Initialize completion system
autoload -Uz compinit
compinit -u

source {stub_path}

# Simulate completion context
words=(aris "")
CURRENT=2

# Call completion function
_aris_complete

# Check if function exists
if (( ${{+functions[_aris_complete_cached]}} )); then
  echo "✓ Completion function loaded successfully"
  
  # Try to call it (suppress all output since we just want to check it runs)
  _aris_complete_cached 2>/dev/null 1>/dev/null && echo "✓ Completion function executed without errors" || echo "⚠ Function executed but returned non-zero (this may be normal)"
else
  echo "❌ Completion function not loaded"
  exit 1
fi
'''
    
    result = subprocess.run(
        ["zsh", "-c", test_script],
        capture_output=True,
        text=True,
        cwd=str(root)
    )
    
    if result.returncode != 0:
        print(f"❌ Completion test failed:")
        print(f"stdout: {result.stdout}")
        print(f"stderr: {result.stderr}")
        return 1
    
    print(result.stdout)
    print()
    print("✅ All zsh completion tests passed!")
    print()
    print("To enable in your shell, add to ~/.zshrc:")
    print(f'  source "{stub_path}"')
    print()
    print("Then restart your shell or run: source ~/.zshrc")
    
    return 0


def test_bash_completion(root: Path) -> int:
    """Test bash completion by validating syntax.

    Args:
        root: ARIS CLI repo root.

    Returns:
        Exit code (0 on success).
    """
    print("Testing bash completion...")
    print()
    
    stub_path = root / "logs" / ".completion_stub.bash"
    cache_path = root / "logs" / ".completion_cache.bash"
    
    if not stub_path.exists():
        print(f"❌ Stub file missing: {stub_path}")
        return 1
    print(f"✓ Stub file exists: {stub_path}")
    
    if not cache_path.exists():
        print(f"❌ Cache file missing: {cache_path}")
        return 1
    print(f"✓ Cache file exists: {cache_path}")
    print()
    
    # Test bash syntax
    import subprocess
    result = subprocess.run(
        ["bash", "-n", str(stub_path)],
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        print(f"❌ Stub syntax error: {result.stderr}")
        return 1
    print(f"✓ Stub syntax is valid")
    
    result = subprocess.run(
        ["bash", "-n", str(cache_path)],
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        print(f"❌ Cache syntax error: {result.stderr}")
        return 1
    print(f"✓ Cache syntax is valid")
    print()
    
    print("✅ All bash completion tests passed!")
    print()
    print("To enable in your shell, add to ~/.bashrc:")
    print(f'  source "{stub_path}"')
    
    return 0


def main():
    """
      aris completion --generate-stub   write shell stub files to logs/
      aris completion --generate-cache — write shell cache files to logs/
      aris completion --test bash       test bash completion
      aris completion --test zsh        test zsh completion
      aris completion bash              print bash stub to stdout
      aris completion zsh               print zsh stub to stdout
    """
    ap = argparse.ArgumentParser(description="Generate shell completion (bash or zsh)")
    ap.add_argument("--root", required=True)
    ap.add_argument("shell", nargs="?", choices=["bash", "zsh"], help="Shell type (bash or zsh)")
    ap.add_argument(
        "--generate-cache",
        action="store_true",
        help="Generate/update completion cache files for both bash and zsh",
    )
    ap.add_argument(
        "--generate-stub",
        action="store_true",
        help="Generate/update completion stub files for both bash and zsh",
    )
    ap.add_argument(
        "--test",
        action="store_true",
        help="Test completion for specified shell (requires shell argument)",
    )
    args = ["--root", str(Path(__file__).parent.parent), "--generate-cache"]
    args = ap.parse_args(args)

    root = Path(args.root)

    if args.generate_cache:
        generate_cache(root)
    elif args.generate_stub:
        # Generate stubs for both shells
        generate_stub(root, "bash")
        generate_stub(root, "zsh")
    elif args.test:
        if not args.shell:
            print("Error: --test requires a shell argument (bash or zsh)", file=sys.stderr)
            return 1
        if args.shell == "zsh":
            return test_zsh_completion(root)
        else:
            return test_bash_completion(root)
    elif args.shell == "bash":
        # Print bash stub to stdout
        print(bash_stub(root))
    elif args.shell == "zsh":
        # Print zsh stub to stdout
        print(zsh_stub(root))
    
    return 0


if __name__ == "__main__":
    sys.exit(main())