# ---------------------------------------------------------------------------
# File: src/completion.py
# ---------------------------------------------------------------------------
"""Shell completion helpers — fast, lazy-loaded architecture (bash only).

Architecture (zero Python calls at shell startup):

1. A tiny bash stub is generated once and sourced by ~/.bashrc.
   It defines a lazy-loading wrapper — NO Python is called at shell startup.

2. On first TAB press, the wrapper sources a pre-generated cache file
   containing the full completion function with all script names baked in.
   The cache file is pure bash — sourcing it is effectively instant.

3. The cache is regenerated by `aris --refresh` or
   `aris completion --generate-cache`.  If the cache file is missing on
   first TAB, it is generated on-the-fly (one-time cost).

4. The wrapper detects when the cache file's mtime changes (single
   stat syscall — nanoseconds) and re-sources it automatically, so
   `aris --refresh` in one terminal updates completions everywhere.

Generated files:
  logs/.completion_stub.bash  — tiny stub sourced by ~/.bashrc
  logs/.completion_cache.bash — full completion data, lazy-loaded on first TAB

Note: zsh completion not supported (too complex with Oh My Zsh).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Stub generator (lightweight — no heavy imports needed)
# ---------------------------------------------------------------------------

def bash_stub(root: Path) -> str:
    """Generate the lightweight bash stub for ~/.bashrc sourcing.

    This stub:
    - Exports ARIS_ROOT
    - Registers a lazy-loading completion function
    - On first TAB: sources the pre-generated cache
    - On subsequent TABs: calls the cached function directly
    - Detects cache file mtime changes to auto-reload after `aris --refresh`

    No Python is called at shell startup or on TAB (unless cache is missing).

    Args:
        root: ARIS CLI repo root.

    Returns:
        Bash stub script as string.
    """
    root_str = str(root)
    return f'''# aris-cli bash completion stub (lazy-loaded, no Python at startup)
# Generated by: aris completion --generate-stub
#
# Source this file in ~/.bashrc:
#   source "{root_str}/logs/.completion_stub.bash"

export ARIS_ROOT="{root_str}"

_aris_complete() {{
  local cache="$ARIS_ROOT/logs/.completion_cache.bash"

  # Check if cache needs (re)loading by comparing file mtime.
  # stat is a single syscall — effectively free on every TAB press.
  local need_load=0
  if [[ -z "${{_ARIS_CACHE_MTIME:-}}" ]]; then
    need_load=1
  elif [[ -f "$cache" ]]; then
    local current_mtime
    current_mtime=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    [[ "$current_mtime" != "$_ARIS_CACHE_MTIME" ]] && need_load=1
  fi

  if [[ $need_load -eq 1 ]]; then
    # Generate cache on-the-fly if missing (one-time cost)
    if [[ ! -f "$cache" ]]; then
      "$ARIS_ROOT/run.sh" completion --generate-cache 2>/dev/null
    fi
    if [[ -f "$cache" ]]; then
      source "$cache"
      _ARIS_CACHE_MTIME=$(stat -c %Y "$cache" 2>/dev/null || stat -f %m "$cache" 2>/dev/null || echo 0)
    fi
  fi

  # Call the cached completion function, or fall back to basics
  if type _aris_complete_cached &>/dev/null; then
    _aris_complete_cached
  else
    COMPREPLY=( $(compgen -W "search completion --refresh --list --help --config --open --add --revert --reset-config" -- "${{COMP_WORDS[COMP_CWORD]}}") )
  fi
}}
complete -o filenames -F _aris_complete aris
'''


# ---------------------------------------------------------------------------
# Cache generator (heavy imports deferred to here)
# ---------------------------------------------------------------------------

def _generate_cache_content(root: Path) -> str:
    """Generate the full completion function for caching.

    Reads from config.yaml only (no filesystem scanning) for speed.
    Called only by --generate-cache, not at shell startup.

    Args:
        root: ARIS CLI repo root.

    Returns:
        Bash completion function as string.
    """
    # Heavy imports — only loaded when actually generating the cache
    from utils import load_config

    cfg = load_config(root)
    
    # Use config data directly - no filesystem scanning
    entries = cfg.get("scripts", [])

    # Collect script names and shortcuts
    names: list[str] = []
    for e in entries:
        name = e.get("name", "")
        if name:
            names.append(name)
        shortcut = e.get("shortcut", "")
        if shortcut:
            names.append(shortcut)
    
    script_names = " ".join(sorted(set(names), key=str.lower))

    # Build exec-paths map
    script_exec_paths: dict[str, str] = {}
    for e in entries:
        name = e.get("name", "")
        exec_path = e.get("execution_path", "")
        if name and exec_path:
            script_exec_paths[name] = exec_path
            shortcut = e.get("shortcut", "")
            if shortcut:
                script_exec_paths[shortcut] = exec_path

    exec_paths_bash = ""
    for name, path in script_exec_paths.items():
        exec_paths_bash += f'  ["{name}"]={path!r}\n'

    return f'''# Auto-generated by: aris completion --generate-cache
# Do not edit manually — regenerated by: aris --refresh

_aris_complete_cached() {{
  local cur prev
  COMPREPLY=()
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  prev="${{COMP_WORDS[COMP_CWORD-1]}}"

  # Subcommands and flags
  local subcmds="search completion --refresh --list --help --config --open --add --revert --reset-config"

  # Map of script names/shortcuts to their execution paths
  declare -A script_paths=(
{exec_paths_bash}  )

  if [[ $COMP_CWORD -eq 1 ]]; then
    # First argument: complete subcommands, flags, and script names
    local all_options="$subcmds {script_names}"
    COMPREPLY=( $(compgen -W "$all_options" -- "$cur") )
    return 0
  elif [[ $COMP_CWORD -ge 2 ]]; then
    # Check if the first argument is a script with an execution_path
    local script_name="${{COMP_WORDS[1]}}"
    if [[ -n "${{script_paths[$script_name]:-}}" ]]; then
      # Complete files/directories from BOTH execution_path and current directory
      local exec_path="${{script_paths[$script_name]}}"
      local current_pwd="$PWD"
      local completions_exec=()
      local completions_cwd=()

      # Get completions from execution_path
      cd "$exec_path" 2>/dev/null && {{
        completions_exec=( $(compgen -f -- "$cur") )
        cd "$current_pwd"
      }}

      # Get completions from current working directory
      completions_cwd=( $(compgen -f -- "$cur") )

      # Combine both sets, removing duplicates
      local combined=()
      local seen=()

      for item in "${{completions_exec[@]}}"; do
        combined+=("$item")
        seen+=("$item")
      done

      for item in "${{completions_cwd[@]}}"; do
        local is_duplicate=0
        for seen_item in "${{seen[@]}}"; do
          if [[ "$item" == "$seen_item" ]]; then
            is_duplicate=1
            break
          fi
        done
        if [[ $is_duplicate -eq 0 ]]; then
          combined+=("$item")
        fi
      done

      COMPREPLY=( "${{combined[@]}}" )
      return 0
    fi
  fi

  # Default: file/directory completion from current directory
  COMPREPLY=( $(compgen -f -- "$cur") )
  return 0
}}
'''


def _generate_zsh_cache_content(root: Path) -> str:
    """Generate zsh-specific cache data.

    Creates a simple newline-separated list for easy loading.
    Reads from config.yaml only (no filesystem scanning) for speed.

    Args:
        root: ARIS CLI repo root.

    Returns:
        Zsh cache data as string.
    """
    # Heavy imports — only loaded when generating cache
    from utils import load_config

    cfg = load_config(root)
    
    # Use config data directly - no filesystem scanning
    entries = cfg.get("scripts", [])

    # Build newline-separated list for _describe - properly escaped
    completions = []
    for e in entries:
        name = e.get("name", "")
        if not name:
            continue
        # Use description from config, defaulting to name
        desc = (e.get("description", name)[:60]).replace("'", "'\\''")
        completions.append(f"{name}:{desc}")
        shortcut = e.get("shortcut", "")
        if shortcut:
            completions.append(f"{shortcut}:{desc} (shortcut)")
    
    # Use literal newlines in the variable (will be read with (@f) flag)
    completions_str = "\\n".join(completions)
    
    # Build exec-paths associative array
    exec_paths_entries = []
    for e in entries:
        name = e.get("name", "")
        exec_path = e.get("execution_path", "")
        if name and exec_path:
            exec_paths_entries.append(f'  ["{name}"]="{exec_path}"')
            shortcut = e.get("shortcut", "")
            if shortcut:
                exec_paths_entries.append(f'  ["{shortcut}"]="{exec_path}"')
    
    exec_paths_zsh = "\n".join(exec_paths_entries)
    
    return f'''# Auto-generated zsh completion cache
# Do not edit manually — regenerated by: aris --refresh

# Newline-separated completions (format: name:description)
_ARIS_COMPLETIONS=$'{completions_str}'

# Associative array: script name -> execution path
typeset -gA _ARIS_EXEC_PATHS
_ARIS_EXEC_PATHS=(
{exec_paths_zsh}
)
'''


def generate_cache(root: Path) -> None:
    """Generate and write the completion cache files (both bash and zsh).

    Args:
        root: ARIS CLI repo root.
    """
    # Generate bash cache
    bash_content = _generate_cache_content(root)
    bash_cache_path = root / "logs" / ".completion_cache.bash"
    bash_cache_path.parent.mkdir(parents=True, exist_ok=True)
    bash_cache_path.write_text(bash_content)
    
    # Generate zsh cache
    zsh_content = _generate_zsh_cache_content(root)
    zsh_cache_path = root / "logs" / ".completion_cache.zsh"
    zsh_cache_path.parent.mkdir(parents=True, exist_ok=True)
    zsh_cache_path.write_text(zsh_content)


def generate_cache(root: Path) -> None:
    """Generate and write the bash completion cache file.

    Args:
        root: ARIS CLI repo root.
    """
    bash_content = _generate_cache_content(root)
    bash_cache_path = root / "logs" / ".completion_cache.bash"
    bash_cache_path.parent.mkdir(parents=True, exist_ok=True)
    bash_cache_path.write_text(bash_content)


def generate_stub(root: Path) -> None:
    """Generate and write the bash completion stub file.

    Args:
        root: ARIS CLI repo root.
    """
    content = bash_stub(root)
    stub_path = root / "logs" / ".completion_stub.bash" #generate-stub   write bash stub file to logs/
    stub_path.parent.mkdir(parents=True, exist_ok=True)
    stub_path.write_text(content)


def main():
    """
      aris completion --generate-stub   write bash stub file to logs/
      aris completion --generate-cache — write bash cache file to logs/
    """
    ap = argparse.ArgumentParser(description="Generate bash shell completion")
    ap.add_argument("--root", required=True)
    ap.add_argument("shell", nargs="?", choices=["bash"], help="Shell type (only bash supported)")
    ap.add_argument(
        "--generate-cache",
        action="store_true",
        help="Generate/update the bash completion cache file",
    )
    ap.add_argument(
        "--generate-stub",
        action="store_true",
        help="Generate/update the bash completion stub file",
    )
    args = ap.parse_args()

    root = Path(args.root)

    if args.generate_cache:
        generate_cache(root)
    elif args.generate_stub:
        generate_stub(root)
    elif args.shell == "bash":
        # Print bash stub to stdout
        print(bash_stub(root))


if __name__ == "__main__":
    main()